# -*- coding: utf-8 -*-
"""Part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oa5RqvKC3FHT-iZT7RNtGgzheKVDZVd3
"""

# Task 1 - Load the dataset into a pandas DataFrame using pd.read_csv() (or equivalent). Print the first five rows, the column data types (.dtypes), and the DataFrame shape.

import pandas as pd
import numpy as np

#Load the dataset into a pandas DataFrame
df = pd.read_csv("/content/drive/MyDrive/SK_Telco_data.csv")

#Print the first five rows
print("First five rows:")
print(df.head())

#Print the column data types (.dtypes)
print("\nColumn data types:")
print(df.dtypes)

#Print the DataFrame shape
print("\nDataFrame shape:")
print(df.shape)

#Task 2 - Null value analysis: Compute the count and percentage of missing values in every column using df.isnull().sum() and (df.isnull().sum() / df.shape[0]) * 100. Report which columns exceed a 20% null rate. For columns below 20% nulls, fill numeric columns with the column median using fillna(df[col].median()). 

#Count nd percentage of missing values
null_value_count = df.isnull().sum()

null_value_percentage = (null_value_count / df.shape[0]) * 100

#Create summary table
null_value_summary = pd.DataFrame({
    'Missing Count': null_value_count,
    'Missing Percentage': null_value_percentage
})

print("Null Value Summary:")
print(null_value_summary)

#Columns exceed a 20% null rate
high_null_cols = null_value_summary[null_value_summary['Missing Percentage'] > 20]

print("\nColumns with exceed a 20% null rate:")
if high_null_cols.empty:
    print("None")
else:
    print(high_null_cols)

#Fill numeric columns with the column median
for col in df.select_dtypes(include=np.number).columns:
    if null_value_percentage[col] <= 20:
        df[col] = df[col].fillna(df[col].median())

print("\nMissing values list:")
print(df.isnull().sum())

#Task 3 - Duplicate detection and removal: Use df.duplicated().sum() to count duplicates. Remove them with df.drop_duplicates(). Report how many rows were removed and whether the removal changes any column's null percentage.


#Count duplicates
duplicate_count = df.duplicated().sum()

print("Number of duplicate :", duplicate_count)

#Calculate null percentages before removing duplicates
null_before = (df.isnull().sum() / len(df)) * 100

#Remove duplicates
df_clean = df.drop_duplicates()

#Calculate null percentages after removing duplicates
null_after = (df_clean.isnull().sum() / len(df_clean)) * 100

#Number of rows removed
rows_removed = len(df) - len(df_clean)

print("\nRows removed:", rows_removed)

#Compare null percentages before and after
comparison = pd.DataFrame({
    "Null % Before": null_before,
    "Null % After": null_after,
    "Changed": null_before != null_after
})

print("\nNull Percentage Comparison:")
print(comparison)

#Check if any column's null percentage changed
if comparison["Changed"].any():
    print("\nThe null percentage changed for the following columns:")
    print(comparison[comparison["Changed"]])
else:
    print("\nRemoving duplicates did not change the null percentage of any column.")

#Update the DataFrame for further analysis
df = df_clean

#Task 4 - Data type correction: Identify at least one column whose inferred dtype is incorrect (e.g., a numeric column stored as object). Convert it using astype() or pd.to_numeric() with errors='coerce'. Convert at least one repetitive string column to category dtype. Report memory usage before and after the conversion using df.memory_usage(deep=True).sum().


import pandas as pd

#Memory usage before conversion
memory_before = df.memory_usage(deep=True).sum()

print("Memory usage before conversion: {:.2f} KB".format(memory_before / 1024))

#Convert object column to numeric
if 'TotalCharges' in df.columns:
    df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
    print("'TotalCharges' converted to numeric.")

#Convert repetitive string column to category
if 'Churn' in df.columns:
    df['Churn'] = df['Churn'].astype('category')
    print("'Churn' converted to category.")

#Memory usage after conversion
memory_after = df.memory_usage(deep=True).sum()

print("\nMemory usage after conversion: {:.2f} KB".format(memory_after / 1024))

print("\nMemory saved: {:.2f} KB".format((memory_before - memory_after) / 1024))

#Verify updated data types
print("\nUpdated Data Types:")
print(df.dtypes)

#Task 5 - Descriptive statistics and skewness: Call df.describe() on all numeric columns. For each numeric column, compute df[col].skew(). Identify and name the column with the highest absolute skewness. Explain in the README what positive vs negative skew means for that column's distribution and what consequence it has for imputing missing values with the mean.

# Descriptive statistics for numeric columns
print("Descriptive Statistics:")
print(df.describe())

# Calculate skewness for numeric columns
numeric_cols = df.select_dtypes(include=np.number).columns

skewness = df[numeric_cols].skew()

print("\nSkewness of Numeric Columns:")
print(skewness)

# Find the column with the highest absolute skewness
highest_skew_col = skewness.abs().idxmax()
highest_skew_value = skewness[highest_skew_col]

print("\nColumn with the highest absolute skewness:")
print(f"{highest_skew_col}: {highest_skew_value:.4f}")


Descriptive statistics for all numeric columns were generated using df.describe(). To assess the shape of each feature's distribution, skewness was calculated individually using df[col].skew(). Among all numeric columns, <column_name> showed the highest absolute skewness value, indicating it deviates the most from a symmetric distribution.
Interpreting Skewness:

Positive skew (skewness > 0): The distribution has a long tail extending toward higher values. Most data points cluster at the lower end, with a small number of unusually large values pulling the tail rightward.
Negative skew (skewness < 0): The distribution has a long tail extending toward lower values. Most data points cluster at the higher end, with a small number of unusually small values pulling the tail leftward.

#Task 6 - Outlier detection with IQR: For at least two numeric columns, compute Q1 (df[col].quantile(0.25)), Q3 (df[col].quantile(0.75)), IQR = Q3 − Q1, lower bound = Q1 − 1.5 × IQR, and upper bound = Q3 + 1.5 × IQR. Count the number of rows that fall outside these bounds. Do not drop the outliers — instead, document them and state in the README whether you will cap them, retain them, or handle them differently in Part 2, and why.

import pandas as pd

#Select two numeric columns
columns_to_check = ["Total day minutes", "Total day charge"]

for col in columns_to_check:
    # Calculate Q1, Q3, and IQR
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    # Calculate lower and upper bounds
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Identify outliers
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(f"\nColumn: {col}")
    print(f"Q1: {Q1:.2f}")
    print(f"Q3: {Q3:.2f}")
    print(f"IQR: {IQR:.2f}")
    print(f"Lower Bound: {lower_bound:.2f}")
    print(f"Upper Bound: {upper_bound:.2f}")
    print(f"Number of Outliers: {len(outliers)}")


#Task 7

import matplotlib.pyplot as plt
import seaborn as sns

# Set plotting style
sns.set(style="whitegrid")


# 1. Line Plot

plt.figure(figsize=(10,5))
plt.plot(df.index, df["Total day minutes"], color="blue")
plt.title("Total Day Minutes by Row Index")
plt.xlabel("Row Index")
plt.ylabel("Total Day Minutes")
plt.show()


# 2. Bar Chart
# Mean Total Day Minutes by Churn

mean_values = df.groupby("Churn")["Total day minutes"].mean()

plt.figure(figsize=(6,5))
plt.bar(mean_values.index.astype(str), mean_values.values, color=["skyblue","orange"])
plt.title("Average Total Day Minutes by Churn")
plt.xlabel("Churn")
plt.ylabel("Average Total Day Minutes")
plt.show()


# 3. Histogram
# Replace with the most skewed column from Task 5

plt.figure(figsize=(8,5))
sns.histplot(df["Total day minutes"], bins=20, kde=True, color="green")
plt.title("Distribution of Total Day Minutes")
plt.xlabel("Total Day Minutes")
plt.ylabel("Frequency")
plt.show()


# 4. Scatter Plot
# Total Day Minutes vs Total Day Charge

plt.figure(figsize=(8,5))
sns.scatterplot(
    data=df,
    x="Total day minutes",
    y="Total day charge"
)
plt.title("Total Day Minutes vs Total Day Charge")
plt.xlabel("Total Day Minutes")
plt.ylabel("Total Day Charge")
plt.show()


# 5. Box Plot
# Total Day Minutes by Churn

plt.figure(figsize=(6,5))
sns.boxplot(
    data=df,
    x="Churn",
    y="Total day minutes"
)
plt.title("Total Day Minutes by Churn")
plt.xlabel("Churn")
plt.ylabel("Total Day Minutes")
plt.show()

#Task 8

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Compute correlation matrix for numeric columns
corr_matrix = df.select_dtypes(include=np.number).corr()

#Plot heat map
plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)

plt.title("Correlation Heat Map")
plt.tight_layout()
plt.show()

#Find the pair of variables with the highest absolute correlation
corr_abs = corr_matrix.abs()

#Remove self-correlations (diagonal)
np.fill_diagonal(corr_abs.values, 0)

#Get the most highly correlated pair
max_corr = corr_abs.unstack().idxmax()
max_value = corr_abs.unstack().max()

print("Highest Absolute Correlation:")
print(f"Variables: {max_corr[0]} and {max_corr[1]}")
print(f"Correlation: {max_value:.4f}")

#(a) Imputation Strategy Comparison
import pandas as pd
import numpy as np

# Select numeric columns
numeric_cols = df.select_dtypes(include=np.number).columns

# Calculate skewness
skewness = df[numeric_cols].skew()

# Two columns with the highest absolute skewness
top2_skew_cols = skewness.abs().sort_values(ascending=False).head(2).index

print("Two Most Skewed Numeric Columns:")
print(skewness.loc[top2_skew_cols])

print("\nMean vs Median Before Imputation")

for col in top2_skew_cols:
    mean_value = df[col].mean()
    median_value = df[col].median()

    print(f"\nColumn: {col}")
    print(f"Mean   : {mean_value:.4f}")
    print(f"Median : {median_value:.4f}")

    # Impute using median
    df[col] = df[col].fillna(median_value)

print("\nRemaining Missing Values")
print(df[top2_skew_cols].isnull().sum())


#(b) Spearman Rank Correlation
import numpy as np
import pandas as pd

# Pearson correlation
pearson_corr = df.select_dtypes(include=np.number).corr(method='pearson')

# Spearman correlation
spearman_corr = df.select_dtypes(include=np.number).corr(method='spearman')

print("Pearson Correlation Matrix")
print(pearson_corr)

print("\nSpearman Correlation Matrix")
print(spearman_corr)

# Difference matrix
difference = (spearman_corr - pearson_corr).abs()

# Remove duplicate pairs and self-correlations
mask = np.triu(np.ones(difference.shape), k=1).astype(bool)

difference_pairs = (
    difference.where(mask)
    .stack()
    .reset_index()
)

difference_pairs.columns = [
    "Variable 1",
    "Variable 2",
    "|Spearman - Pearson|"
]

difference_pairs = difference_pairs.sort_values(
    by="|Spearman - Pearson|",
    ascending=False
)

print("\nTop Three Differences")
print(difference_pairs.head(3))


#(c) Grouped Aggregation
categorical_col = "Churn"
numeric_col = "Total day minutes"

group_stats = (
    df.groupby(categorical_col)[numeric_col]
      .agg(["mean", "std", "count"])
)

print(group_stats)

highest_mean_group = group_stats["mean"].idxmax()
highest_std_group = group_stats["std"].idxmax()

highest_mean = group_stats["mean"].max()
lowest_mean = group_stats["mean"].min()

ratio = highest_mean / lowest_mean

print("\nGroup with Highest Mean:", highest_mean_group)
print("Group with Highest Standard Deviation:", highest_std_group)
print("Highest Mean / Lowest Mean Ratio:", round(ratio,2))


#Task 10
# Save the cleaned dataset
df.to_csv("cleaned_data.csv", index=False)

print("Cleaned dataset saved successfully as 'cleaned_data.csv'.")

from google.colab import files

files.download("cleaned_data.csv")